### ISSUE TITLE
App ID for AdMob - Firebase

### ISSUE THREAD

**Issue by plucian** [FrogSquare/GodotFireBase#20]
Hey guys, I'm trying to use your Firbase modules for Godot, since it integrate, everything I need.
However I have couple of questions:
Where do I enter my App ID for AdMob ?
Where can I find the: godot-firebase-config.json file ? is the google-services.json you already mentioned or is something different ?
Is there and idea of having the AdMob module work for iOS ? (maybe all other modules to work with apple products ?)
thanks for all the great work you guys are doing !

**Comment by RameshRavone** [comment]
App Id was never implemented, but the latest commit just introduced id,
first pull the latest repo and add `AppId` to your json under `Ads`

**Comment by plucian** [comment]
well.. I cannot find this "my json", that you speak of. Should I create one with the content provided in help? 
thanks and sorry for the noob questions.

**Comment by RameshRavone** [comment]
there is an example in README,

On 04-Dec-2017 11:52 am, "Lucian" <notifications@github.com> wrote:

well.. I cannot find this "my json", that you speak of. Should I create one
with the content provided in help?
thanks and sorry for the noob questions.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/FrogSquare/GodotFireBase/issues/20#issuecomment-348870615>,
or mute the thread
