### ISSUE TITLE
Gradle build fails for export templates

### ISSUE THREAD

**Issue by HummusSamurai** [FrogSquare/GodotFireBase#34]
I am building export templates for godot 2.1 and after running scons, gradle fails.

- I added "google-services.json" from my firebase project to godot_root/platform/android/java as required.

- I changed the godot_game/engine.cfg line to:
`modules="org/godotengine/godot/FireBase,org/godotengine/godot/SQLBridge,org/godotengine/godot/GooglePlay"`

- I added my app ID to the config.py file in /modules/GooglePlayService/
`app_id = "984479825900"`

The error I am getting is this:

```
./gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'java'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find com.google.firebase:firebase-core:15.0.1.
     Required by:
         project :
   > Could not find com.google.firebase:firebase-core:15.0.1.
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s

```

My

**Comment by MatiasVME** [comment]
mmmm...

I am using this command and all work fine -->

```scons platform=x11 -j4; scons platform=android target=release -j4; scons platform=android target=release_debug -j4; cd platform/android/java/ ; ./gradlew build; cd ../../..```

**Comment by HummusSamurai** [comment]
Thank you for replying! Are you using godot 2.1 as well?

**Comment by MatiasVME** [comment]
yes, I am using 2.1

**Comment by RameshRavone** [comment]
I don't even get it why would the builder look for `firebase-core:15.0.1`, aren't we still using `11.6.0`
I do wish to update that to `16.0.3` but this needs some changes in `ApplicationVariants` to match `google-services:4.1.0`

**Comment by RameshRavone** [comment]
Bumped deps version to the latest, try pulling the latest commits

**Comment by HummusSamurai** [comment]
Thank you!

Now it builds but I get the following error when trying to export from godot:

`No pending exception expected: java.lang.ClassNotFoundException: Didn't find class "org/godotengine/godot/FireBase" on path: DexPathList[[zip file "/data/app/org.godotengine.hookmonkey-H_-aFzXvcglZQnW_lnmgbg==/base.apk"],nativeLibraryDirectories=[/data/app/org.godotengine.hookmonkey-H_-aFzXvcglZQnW_lnmgbg==/lib/arm64, /data/app/org.godotengine.hookmonkey-H_-aFzXvcglZQnW_lnmgbg==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /product/lib64]]'
`
My modules folder has /FireBase/, /GodotGoogleService/, and /GodotSQL/ as all the packages indicate.

**Comment by RameshRavone** [comment]
And the module to engine.cfg and relaunch the Godot editor

**Comment by HummusSamurai** [comment]
Still doesn't work. I did everything again to check, I even did git clean to make sure.

**Comment by MatiasVME** [comment]
- Did you build the template for debug?
- Did you put the android templates in the templates folder of your godot version?
In my case: /home/matias/.godot/templates/ . Templates are: android_debug.apk and android_release.apk
- I'm not sure about this, but I followed in the footsteps of this, too: https://godotengine.org/article/fixing-godot-games-published-google-play
- You have the: godot-firebase-config.json in your res:// directory ?
- Do you have this? :
![screenshot_20180913_113546](https://user-images.githubusercontent.com/342117/45495227-34bb8400-b749-11e8-9fb6-81b7087d5c78.png)

I don't know what else it could be :S

**Comment by HummusSamurai** [comment]
- I built the template for release, am I supposed to build it for debug?
- The templates are in the project folder but they are set up in the export options under "custom package" which has worked before for other modules's templates.
- I am able to use my godot version with other modules so I know the article is not related to my problem.
- I have godot-firebase-config.json in my res directory.
- I added *.json to included export files.

Perhaps it's related to the earlier problem that FrogSquare fixed?

**Comment by iRadEntertainment** [comment]
There is still something else wrong with the gradle build. I'm not good with java so I cannot relly point out which is the real problem here. But it seems to miss a method in the script.

I have the latest Gradle installed at the moment.

Here is my log from the template build running `gradlew build --scan:`
`> Configure project :
WARNING: Configuration 'compile' is obsolete and has been replaced with 'impleme
ntation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.androi
d.com/r/tools/update-dependency-configurations.html
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCol
lection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCol
lection)

> Task :processDebugGoogleServices
Parsing json file: C:\Godot\platform\android\java\google-services.json

> Task :compileDebugJavaWithJavac FAILED
C:\Godot\modules\FireBase\android\storage\UploadService.java:130: error: cannot
find symbol
                                Uri downloadUri = taskSnapshot.getMetadata().get
DownloadUrl();
                                                                            ^
  symbol:   method getDownloadUrl()
  location: class StorageMetadata
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Godot\modules\FireBase\android\auth\FacebookSignIn.java uses unchecked
or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 50s
17 actionable tasks: 17 executed
`

**Comment by RameshRavone** [comment]
[commit](https://github.com/FrogSquare/GodotFireBase/commit/8acdffbc0dd565ceb3a6cdefffc13500a4b0b6e1) Fixed this
